package com.example.mainactivity

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.PagerSnapHelper
import androidx.recyclerview.widget.RecyclerView
import com.example.mainactivity.databinding.ActivityMainBinding
import com.google.android.material.tabs.TabLayout

// Variable to hold the binding object that is generated by the view binding KF 11/17/2023
@SuppressLint("StaticFieldLeak")
private lateinit var binding: ActivityMainBinding

class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Create a dataset
        val weatherItems = listOf(
            WeatherItem("Miami, FL", "Dec 23, Tue", R.drawable.therm_icon_transparent, "21°C",R.drawable.weather_icon , "6:00 AM", "0.006 in" , "8:00 PM"),
            WeatherItem("New York, NY", "Dec 24, Fri", R.drawable.therm_icon_transparent, "11°C",R.drawable.weather_icon , "5:00 AM", "0.20 in" ,"7:00 PM"),
            WeatherItem("Seattle, WA", "Oct 26, Thurs", R.drawable.therm_icon_transparent, "6°C",R.drawable.weather_icon , "9:00 AM", "0.63 in " , "3:00 PM"),
            WeatherItem("LA, CA", "Dec 28, Wed", R.drawable.therm_icon_transparent, "71°C",R.drawable.weather_icon , "6:00 AM", "20 in" ,"8:00 PM"),
            WeatherItem("Miami, FL", "April 23, Sat", R.drawable.therm_icon_transparent, "50°C",R.drawable.weather_icon , "5:00 AM", "6.3 in","9:00 PM")
        )

        // Set up the RecyclerView with a horizontal LinearLayoutManager and an adapter
        binding.horizontalCardRecyclerview.apply {
            layoutManager = LinearLayoutManager(this@MainActivity, LinearLayoutManager.HORIZONTAL, false)
            adapter = WeatherAdapter(weatherItems)

            // Attach the PagerSnapHelper to enable snapping behavior
            val snapHelper = PagerSnapHelper()
            snapHelper.attachToRecyclerView(this)
        }

        // Initialize the TabLayout and add a tab for each item in the RecyclerView
        val tabLayout = binding.tabDots
        for (i in weatherItems.indices) {
            tabLayout.addTab(tabLayout.newTab())
        }

        // Add an OnScrollListener to the RecyclerView to update the selected tab
        binding.horizontalCardRecyclerview.addOnScrollListener(object : RecyclerView.OnScrollListener() {
            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
                super.onScrolled(recyclerView, dx, dy)
                val layoutManager = recyclerView.layoutManager as LinearLayoutManager
                val position = layoutManager.findFirstCompletelyVisibleItemPosition()
                if (position != RecyclerView.NO_POSITION) {
                    tabLayout.selectTab(tabLayout.getTabAt(position))
                }
            }
        })
    }

}

