package com.example.mainactivity

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.example.mainactivity.databinding.ActivityMainBinding

// Variable to hold the binding object that is generated by the view binding KF 11/17/2023
private lateinit var binding: ActivityMainBinding

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // Inflate the layout XML file and return a binding object instance KF 11/17/2023
        binding = ActivityMainBinding.inflate(layoutInflater)

        // Set the content view of the Activity to be the root view of the layout KF 11/17/2023
        val view = binding.root

        // Pass the view to setContentView() KF 11/17/2023
        setContentView(view)

        // Removed the following line since view binding is used KF 11/17/2023
        // setContentView(R.layout.activity_main)
    }
}